apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-nginx
spec:
  selector:
    matchLabels:
      app: old-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: old-nginx
    spec:
      containers:
      - name: old-nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: old
          mountPath: /usr/share/nginx/html
      volumes:
      - name: old
        hostPath:
          path: /www/old
---
apiVersion: v1
kind: Service
metadata:
  name: old-nginx
spec:
  selector:
    app: old-nginx
  ports:
  - name: old-nginx
    port: 80
    targetPort: 80
